CREATE TABLE IF NOT EXISTS Users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    email VARCHAR(30) NOT NULL CHECK (email LIKE '%@%') UNIQUE
);
CREATE TABLE IF NOT EXISTS Phone (
    id SERIAL PRIMARY KEY,
    phone BIGINT NOT NULL CHECK(phone > 10000000000) UNIQUE,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);